### ISSUE TITLE
Rename MethodDecl to FunctionDecl

### ISSUE THREAD

**Issue by atennapel** [MetaBorgCube/metaborg-js#4]
Javascript doesn't really have methods, the closest thing is function properties like:

```
var Person = {name: 'Albert'};
Person.getName = function() {return this.name};
```

But those are just a property expression followed by an assignment expression with an anonymous function. So let's rename MethodDecl to FunctionDecl to keep things more in line with Javascript.

**Comment by besuikerd** [comment]
constructor is renamed in the revised syntax now
